config/routes.rb
Blog::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end
    
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  root :to => 'pages#home'
  

end

app/views/shared/_comment_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label "Comment"%>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="posts" summary="User posts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <a href="<%= user_path(current_user) %>">
    <%= gravatar_for feed_item.user, :size => 60 %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item %>
    </span>
  </td>
  <td class="post">
    <span class="title"><%= link_to feed_item.title, feed_item %></span>
    <span class="content">
      <%= raw(truncate(feed_item.content, :length => 200,
                       :omission => "... #{link_to('[more]', feed_item)}")) %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    <a href="<%= post_path(feed_item) %>">
      <span class="stat">
        <%= pluralize(feed_item.comments.count, "comment") %>
      </span>
    </a>
    <span>
      <% if current_user?(feed_item.user) %>
        <%= link_to "delete", feed_item, :method => :delete,
                                         :confirm => "You sure?",
                                         :title => feed_item.title %>
    </span>
      <% end %>
  </td>
</tr>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_field :title %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_sign_up_home.html.erb
<h1>A Blog</h1>

  <p>
    Will &amp; Jennica</a>
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_signed_in_home.html.erb
<table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="post">Quoi de neuf?</h1>
        <%= render 'shared/post_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
</table>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>
<div class="user_info">
  <a href="<%= user_path(@user) %>">
    <%= gravatar_for @user, :size => 60 %>
    <span class="user_name">
      <%= @user.name %>
    </span>
    <span class="posts">
      <%= pluralize(@user.posts.count, "post") %>
    </span>
  </a>
</div>